@startuml

class 顧客 {
    名称
    住所
    電話番号
}

class 請求方法 {

}

class 銀行口座引き落とし請求 {
    銀行コード
    支店コード
    口座種別
    口座番号
    名義人指名
}

class カード引き落とし請求 {
    カード番号
    有効期限
    名義人指名
}

class 請求書請求 {
    請求書住所
    請求書指名
}

顧客 "1"-"1" 請求方法
銀行口座引き落とし請求 -up-|> 請求方法
カード引き落とし請求 -up-|> 請求方法
請求書請求 -up-|> 請求方法


@enduml