@startuml
class Rectangle {
  +width
  +height
  +setWidth()
  +setHeight()
  +getArea()
}

class Square {
  +width
  +height
  +setWidth()
  +setHeight()
  +getArea()
}

Rectangle <--- Square

@enduml
